# NumPy

Python içerisinde bir kütüphanedir. Büyük ve çok boyutlu diziler ile matrisler üzerinde çalışılabilecek üst düzey matematik koleksiyonu sunar.

In [2]:
# İlk olarak import edilir. 
# Kişiye bağlı kullanımdır ama literatürde np olarak adlandırılır. 

import numpy as np 

Matris olaran `array` bir veri depolama çeşididir. NumPy'ın veriyi kullanabilmesi için veriler `array` haline getirilir.

In [3]:
veri = [[1,2,3],[4,5,6],[7,8,9]]

a = np.array(veri) # Eldeki veriyi array formatına çevirir.

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Diğer veri türlerinde olduğu gibi `array` içindeki indexlere de ulaşabiliriz.

In [5]:
print(a[0])    # 0. indexteki veriyi alır.
print(a[1,2])  # 1. indexin 2. verisini alır.

[1 2 3]
6


Fancy Index ile bir `array` içinden eleman seçmek için index değerleri liste veya array verilerek indexleme yapılabilir.

In [104]:
f = np.arange(0, 500, 3)

index_deger = [2, 34, 23, 40]

f[index_deger]

array([  6, 102,  69, 120])

`ndim` boyut sayısını, `shape` boyut bilgisini, `size` toplam eleman sayısını, `dytpe` veri tipini verir.

In [94]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(5,)
5
int64


## Bazı temel fonksiyonlar

**`arange()`**

Verilen iki sayı arasındaki değerleri `array` olarak depolar.

In [9]:
print(np.arange(2,30)) 
print(np.arange(2,30,3)) # Verilen değer kadar atlayarak da depolar.

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]
[ 2  5  8 11 14 17 20 23 26 29]


---

**`zeros()` , `ones()` , `full()` ve `eye()`**

In [10]:
print(np.zeros(30)) # Belirtilen miktar kadar 0 oluşturur.
print(np.ones(20))  # Belirtilen miktar kadar 1 oluşturur.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Bu fonksiyonlarda `array` boyutlarını düzenleyebiliriz.

In [13]:
np.zeros((10,5)) # Çift parantez ile boyut düzenlendi.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
np.full((3,4),8) # Belirli değerde matris oluşturur.

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [14]:
np.eye(5) # 5x5'lik birim matris oluşturur.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

**`linspace()`**

İlk iki değer arasında olan sayıları üçüncü sayıya eşit parçalar olarak dağıtır.

In [18]:
np.linspace(2,50,10)

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

---

**`random()`**

Rastgele sayı veya sayırlar üretir.

In [45]:
print(np.random.randint(0,100))   # 0 ile 100 arasında rastgele bir sayı üretir.
print(np.random.randint(100))     # Başa sıfır yazılmadığında da üsttekiyle aynı işlevle çalışır.
print(np.random.randint(0,100,4)) # Diğer fonksiyonlarda olduğu argümanla da sayı üretir.
print(np.random.rand(5))          # 0 ile 1 arasında 5 sayı üretir.

49
46
[94 36 88 80]
[0.93703906 0.51898989 0.20022832 0.79946758 0.43781222]


---

**`reshape()`**

Veriye matris olarak istenilen şekli verir.

In [34]:
sekil = np.arange(30)

print(sekil)              # Tek boyutlu yani vektörel.
print(sekil.reshape(5,6)) # Çok boyutlu yani matris.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


---

**`concatenate()`**

In [95]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = [7,8,9]

np.concatenate([x,y,z]) # Değerleri birleştirir.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

---

**`sort()`** ve **`argsort()`**

In [101]:
v = np.array([34, 4, 1, 9, 10])

print(v)

print(np.sort(v))    # NumPy'daki metotla sıralar, array orjinalinde değişiklik yapmaz. v.sort() olsaydı kalıcı değişirdi.
print(np.argsort(v)) # Sıralama sonrası değerlerin eski index değerlerini, yani nerede olduklarını döndürür.

[34  4  1  9 10]
[ 1  4  9 10 34]
[2 1 3 4 0]


## Bazı istatistik temellli fonksiyonlar

**`cumsum()` , `min()` , `max()` , `sum()` , `std()` , `mean()` , `median()`**

In [71]:
stats = np.arange(13,50)

print(stats)
print(np.cumsum(stats)) # Kümülatif toplam.
print(np.sum(stats))    # Tümünün toplamı.
print(np.min(stats))    # Mininum değer.
print(np.max(stats))    # Maksimum değer.
print(np.std(stats))    # Standart sapması.
print(np.var(stats))    # Varyansı.
print(np.mean(stats))   # Ortalaması.
print(np.median(stats)) # Ortanca değeri.

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37 38 39 40 41 42 43 44 45 46 47 48 49]
[  13   27   42   58   75   93  112  132  153  175  198  222  247  273
  300  328  357  387  418  450  483  517  552  588  625  663  702  742
  783  825  868  912  957 1003 1050 1098 1147]
1147
13
49
10.677078252031311
114.0
31.0
31.0


---

**`argmax()`** ve **`argmin()`**

In [70]:
print(np.argmax(stats)) # En büyük değerin indexini verir.
print(np.argmin(stats)) # En küçük değerin indexini verir.

36
0


## Dilimleme

- Array yapılarını dilimleme (slicing) listelerdeki gibidir. 
- Dilimleme işlemleri `[satır:sütun]` şeklinde çalışır. 
- İki boyutlu array içinden dilimleme işlemi de `[satır:satır,sütun:sütun]` şeklinde çalışır. 
- Aslında alt array oluşturur.

In [78]:
dilim = np.arange(0,100)

dilim[2:7]

array([2, 3, 4, 5, 6])

In [85]:
ikinci_dilim = np.arange(0,30).reshape(5,6)

print(ikinci_dilim)
print(ikinci_dilim[3,:])     # Satırın tamamını alır.
print(ikinci_dilim[:,3])     # Sütunun tamamını alır.
print(ikinci_dilim[0:2,1:4]) # Matrislerde virgül kesişim kümesi gibi çalışır.

ikinci_dilim[1:4,0:3] = 99   # Değerler için atama işlemi de yapılabilir.

print(ikinci_dilim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[18 19 20 21 22 23]
[ 3  9 15 21 27]
[[1 2 3]
 [7 8 9]]
[[ 0  1  2  3  4  5]
 [99 99 99  9 10 11]
 [99 99 99 15 16 17]
 [99 99 99 21 22 23]
 [24 25 26 27 28 29]]


Alt arraylerde işlem yaparken ana arrayi etkilememek için alt array `copy()` ile çoğaltılarak işlem yapılır.

In [103]:
print(ikinci_dilim)

print(ikinci_dilim[0:2,1:4])

alt = ikinci_dilim[0:2,1:4].copy()

alt[0:1,1:] = 8888 # Alt arrayde değişiklik yapıyoruz.

print(alt)

print(ikinci_dilim) # Ama yaptığımız değişiklik ana arrayi etkilemiyor.

[[ 0  1  2  3  4  5]
 [99 99 99  9 10 11]
 [99 99 99 15 16 17]
 [99 99 99 21 22 23]
 [24 25 26 27 28 29]]
[[ 1  2  3]
 [99 99  9]]
[[   1 8888 8888]
 [  99   99    9]]
[[ 0  1  2  3  4  5]
 [99 99 99  9 10 11]
 [99 99 99 15 16 17]
 [99 99 99 21 22 23]
 [24 25 26 27 28 29]]


Verileri analiz ederken ihtiyaç halindeki sorgulamalarda değerlere `True` veya `False` atanabilir.

In [86]:
ikinci_dilim > 20

array([[False, False, False, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

## Matematiksel operatörler

Arrayler üzerinde arrayler arasında da dahil matematik işlemleri yapılabilir.

In [90]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(a)
print(a-1)
print(a+1)
print(a*3)
print(a**2)
print(a/2)

print(a*b)

[1 2 3 4 5]
[0 1 2 3 4]
[2 3 4 5 6]
[ 3  6  9 12 15]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]
[ 6 14 24 36 50]


Operatörlerin fonksiyonları da bulunur.

In [88]:
print(np.add(a,2))      # Toplama
print(np.subtract(a,2)) # Çıkarma
print(np.multiply(a,2)) # Çarpma
print(np.divide(a,2))   # Bölme
print(np.power(a,2))    # Üs

[2 3 4 5 6]
[-2 -1  0  1  2]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[ 0  1  4  9 16]
